### ISSUE TITLE
I can't see FakeLogonScreen.exe and FakeLogonScreenToFile.exe

### ISSUE THREAD

**Issue by Nicola-Molinari** [bitsadmin/fakelogonscreen#11]
Can you link me this file? thanks

**Comment by bitsadmin** [comment]
Please check the [Releases](https://github.com/bitsadmin/fakelogonscreen/releases) page where you can download the **fakelogonscreen_trunk.zip** file which contains both executables. Note that antivirus programs might trigger when scanning the zip and automatically remove both executables from it.
