### ISSUE TITLE
login details

### ISSUE THREAD

**Issue by truesamurai** [bitsadmin/fakelogonscreen#2]
When I execute FakeLogonScreen.exe, where is the password saved?

**Comment by bitsadmin** [comment]
Check the [README](https://github.com/bitsadmin/fakelogonscreen/blob/master/README.md):
- FakeLogonScreen.exe: Writes output to console which for example is compatible with Cobalt Strike
- FakeLogonScreenToFile.exe: Writes output to console and `%LOCALAPPDATA%\Microsoft\user.db`
