### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Zagreus9723** [bitsadmin/fakelogonscreen#4]
How can I change where the user.db file is stored?

**Comment by bitsadmin** [comment]
At this moment there is no such functionality implemented, so there are two options:
* Add the functionality so an optional commandline parameter can be specified for the `FakeLogonScreenToFile.exe` executable in which the output file can be specified;
* Update and recompile the source code so a custom location is used to store the credentials.

Hope that helps!

**Comment by Zagreus9723** [comment]
I have looked very well and can't seem to find the path where it stores the output file. Can you tell me what file and line?

**Comment by bitsadmin** [comment]
Sure, here you go:
https://github.com/bitsadmin/fakelogonscreen/blob/master/Source/LogonScreen.cs#L77

You can replace that line with for example:
`string path = @"C:\Windows\Temp\tmp9666.tmp";`

**Comment by Zagreus9723** [comment]
Thanks!
