### ISSUE TITLE
Google Chrome blocking release download

### ISSUE THREAD

**Issue by Berkeli123** [bitsadmin/fakelogonscreen#5]
Chrome says "download is dangerous"and prevents downloading it.

**Comment by bitsadmin** [comment]
Makes sense as FakeLogonScreen is a hacking tool which are frequently blocked by AV products, and apparently also by the browser.

You can work around this by opening the Chrome **Downloads** screen (Ctrl + J) and choosing **Keep dangerous file**.

![image](https://user-images.githubusercontent.com/9055728/129461888-e8709e83-dab4-4816-bca3-7a75a2e2262c.png)
