### ISSUE TITLE
Logon screen closing

### ISSUE THREAD

**Issue by Zoink1234** [bitsadmin/fakelogonscreen#6]
Every time I open the logon screen, after a few seconds it will just close automatically, I already have all my antivirus apps and features disabled.

**Comment by bitsadmin** [comment]
Hi Zoink1234, this is the first time I hear about such issue. Have you tried launching fakelogonscreen from Visual Studio? Maybe Visual Studio will then show you the code at which it crashes (if it indeed crashes). Alternatively try it on a different (virtual) machine and see if you can somehow determine whether any (security) software somehow causes this behavior.
